import { Knex } from "knex";

const COUNTRIES = [
  { name: "Afganistán", id: "AF" },
  { name: "Albania", id: "AL" },
  { name: "Alemania", id: "DE" },
  { name: "Andorra", id: "AD" },
  { name: "Angola", id: "AO" },
  { name: "Antigua y Barbuda", id: "AG" },
  { name: "Arabia Saudita", id: "SA" },
  { name: "Argelia", id: "DZ" },
  { name: "Argentina", id: "AR" },
  { name: "Armenia", id: "AM" },
  { name: "Australia", id: "AU" },
  { name: "Austria", id: "AT" },
  { name: "Azerbaiyán", id: "AZ" },
  { name: "Bahamas", id: "BS" },
  { name: "Bangladés", id: "BD" },
  { name: "Barbados", id: "BB" },
  { name: "Baréin", id: "BH" },
  { name: "Bélgica", id: "BE" },
  { name: "Belice", id: "BZ" },
  { name: "Benín", id: "BJ" },
  { name: "Bielorrusia", id: "BY" },
  { name: "Birmania", id: "MM" },
  { name: "Bolivia", id: "BO" },
  { name: "Bosnia y Herzegovina", id: "BA" },
  { name: "Botsuana", id: "BW" },
  { name: "Brasil", id: "BR" },
  { name: "Brunéi", id: "BN" },
  { name: "Bulgaria", id: "BG" },
  { name: "Burkina Faso", id: "BF" },
  { name: "Burundi", id: "BI" },
  { name: "Bután", id: "BT" },
  { name: "Cabo Verde", id: "CV" },
  { name: "Camboya", id: "KH" },
  { name: "Camerún", id: "CM" },
  { name: "Canadá", id: "CA" },
  { name: "Catar", id: "QA" },
  { name: "Chad", id: "TD" },
  { name: "Chile", id: "CL" },
  { name: "China", id: "CN" },
  { name: "Chipre", id: "CY" },
  { name: "Ciudad del Vaticano", id: "VA" },
  { name: "Colombia", id: "CO" },
  { name: "Comoras", id: "KM" },
  { name: "Corea del Norte", id: "KP" },
  { name: "Corea del Sur", id: "KR" },
  { name: "Costa de Marfil", id: "CI" },
  { name: "Costa Rica", id: "CR" },
  { name: "Croacia", id: "HR" },
  { name: "Cuba", id: "CU" },
  { name: "Dinamarca", id: "DK" },
  { name: "Dominica", id: "DM" },
  { name: "Ecuador", id: "EC" },
  { name: "Egipto", id: "EG" },
  { name: "El Salvador", id: "SV" },
  { name: "Emiratos Árabes Unidos", id: "AE" },
  { name: "Eritrea", id: "ER" },
  { name: "Eslovaquia", id: "SK" },
  { name: "Eslovenia", id: "SI" },
  { name: "España", id: "ES" },
  { name: "Estados Unidos", id: "US" },
  { name: "Estonia", id: "EE" },
  { name: "Etiopía", id: "ET" },
  { name: "Filipinas", id: "PH" },
  { name: "Finlandia", id: "FI" },
  { name: "Fiyi", id: "FJ" },
  { name: "Francia", id: "FR" },
  { name: "Gabón", id: "GA" },
  { name: "Gambia", id: "GM" },
  { name: "Georgia", id: "GE" },
  { name: "Ghana", id: "GH" },
  { name: "Granada", id: "GD" },
  { name: "Grecia", id: "GR" },
  { name: "Guatemala", id: "GT" },
  { name: "Guyana", id: "GY" },
  { name: "Guinea", id: "GN" },
  { name: "Guinea ecuatorial", id: "GQ" },
  { name: "Guinea-Bisáu", id: "GW" },
  { name: "Haití", id: "HT" },
  { name: "Honduras", id: "HN" },
  { name: "Hungría", id: "HU" },
  { name: "India", id: "IN" },
  { name: "Indonesia", id: "ID" },
  { name: "Irak", id: "IQ" },
  { name: "Irán", id: "IR" },
  { name: "Irlanda", id: "IE" },
  { name: "Islandia", id: "IS" },
  { name: "Islas Marshall", id: "MH" },
  { name: "Islas Salomón", id: "SB" },
  { name: "Israel", id: "IL" },
  { name: "Italia", id: "IT" },
  { name: "Jamaica", id: "JM" },
  { name: "Japón", id: "JP" },
  { name: "Jordania", id: "JO" },
  { name: "Kazajistán", id: "KZ" },
  { name: "Kenia", id: "KE" },
  { name: "Kirguistán", id: "KG" },
  { name: "Kiribati", id: "KI" },
  { name: "Kuwait", id: "KW" },
  { name: "Laos", id: "LA" },
  { name: "Lesoto", id: "LS" },
  { name: "Letonia", id: "LV" },
  { name: "Líbano", id: "LB" },
  { name: "Liberia", id: "LR" },
  { name: "Libia", id: "LY" },
  { name: "Liechtenstein", id: "LI" },
  { name: "Lituania", id: "LT" },
  { name: "Luxemburgo", id: "LU" },
  { name: "Macedonia del Norte", id: "MK" },
  { name: "Madagascar", id: "MG" },
  { name: "Malasia", id: "MY" },
  { name: "Malaui", id: "MW" },
  { name: "Maldivas", id: "MV" },
  { name: "Malí", id: "ML" },
  { name: "Malta", id: "MT" },
  { name: "Marruecos", id: "MA" },
  { name: "Mauricio", id: "MU" },
  { name: "Mauritania", id: "MR" },
  { name: "México", id: "MX" },
  { name: "Micronesia", id: "FM" },
  { name: "Moldavia", id: "MD" },
  { name: "Mónaco", id: "MC" },
  { name: "Mongolia", id: "MN" },
  { name: "Montenegro", id: "ME" },
  { name: "Mozambique", id: "MZ" },
  { name: "Namibia", id: "NA" },
  { name: "Nauru", id: "NR" },
  { name: "Nepal", id: "NP" },
  { name: "Nicaragua", id: "NI" },
  { name: "Níger", id: "NE" },
  { name: "Nigeria", id: "NG" },
  { name: "Noruega", id: "NO" },
  { name: "Nueva Zelanda", id: "NZ" },
  { name: "Omán", id: "OM" },
  { name: "Países Bajos", id: "NL" },
  { name: "Pakistán", id: "PK" },
  { name: "Palaos", id: "PW" },
  { name: "Panamá", id: "PA" },
  { name: "Papúa Nueva Guinea", id: "PG" },
  { name: "Paraguay", id: "PY" },
  { name: "Perú", id: "PE" },
  { name: "Polonia", id: "PL" },
  { name: "Portugal", id: "PT" },
  { name: "Reino Unido", id: "GB" },
  { name: "República Centroafricana", id: "CF" },
  { name: "República Checa", id: "CZ" },
  { name: "República del Congo", id: "CG" },
  { name: "República Democrática del Congo", id: "CD" },
  { name: "República Dominicana", id: "DO" },
  { name: "Ruanda", id: "RW" },
  { name: "Rumanía", id: "RO" },
  { name: "Rusia", id: "RU" },
  { name: "Samoa", id: "WS" },
  { name: "San Cristóbal y Nieves", id: "KN" },
  { name: "San Marino", id: "SM" },
  { name: "San Vicente y las Granadinas", id: "VC" },
  { name: "Santa Lucía", id: "LC" },
  { name: "Santo Tomé y Príncipe", id: "ST" },
  { name: "Senegal", id: "SN" },
  { name: "Serbia", id: "RS" },
  { name: "Seychelles", id: "SC" },
  { name: "Sierra Leona", id: "SL" },
  { name: "Singapur", id: "SG" },
  { name: "Siria", id: "SY" },
  { name: "Somalia", id: "SO" },
  { name: "Sri Lanka", id: "LK" },
  { name: "Suazilandia", id: "SZ" },
  { name: "Sudáfrica", id: "ZA" },
  { name: "Sudán", id: "SD" },
  { name: "Sudán del Sur", id: "SS" },
  { name: "Suecia", id: "SE" },
  { name: "Suiza", id: "CH" },
  { name: "Surinam", id: "SR" },
  { name: "Tailandia", id: "TH" },
  { name: "Tanzania", id: "TZ" },
  { name: "Tayikistán", id: "TJ" },
  { name: "Timor Oriental", id: "TL" },
  { name: "Togo", id: "TG" },
  { name: "Tonga", id: "TO" },
  { name: "Trinidad y Tobago", id: "TT" },
  { name: "Túnez", id: "TN" },
  { name: "Turkmenistán", id: "TM" },
  { name: "Turquía", id: "TR" },
  { name: "Tuvalu", id: "TV" },
  { name: "Ucrania", id: "UA" },
  { name: "Uganda", id: "UG" },
  { name: "Uruguay", id: "UY" },
  { name: "Uzbekistán", id: "UZ" },
  { name: "Vanuatu", id: "VU" },
  { name: "Venezuela", id: "VE" },
  { name: "Vietnam", id: "VN" },
  { name: "Yemen", id: "YE" },
  { name: "Yibuti", id: "DJ" },
  { name: "Zambia", id: "ZM" },
  { name: "Zimbabue", id: "ZW" }
];

export async function up(knex: Knex): Promise<void> {
  const trips = await knex('trips').select('id', 'countries');

  for (const trip of trips) {
    if (trip.countries && Array.isArray(trip.countries)) {
      const updatedCountries = trip.countries.map((c: string) => {
        const found = COUNTRIES.find(country => country.name === c);
        return found ? found.id : c;
      });

      await knex('trips')
        .where('id', trip.id)
        .update({
          countries: JSON.stringify(updatedCountries)
        });
    }
  }
}

export async function down(knex: Knex): Promise<void> {
  const trips = await knex('trips').select('id', 'countries');

  for (const trip of trips) {
    if (trip.countries && Array.isArray(trip.countries)) {
      const rolledBackCountries = trip.countries.map((c: string) => {
        const found = COUNTRIES.find(country => country.id === c);
        return found ? found.name : c;
      });

      await knex('trips')
        .where('id', trip.id)
        .update({
          countries: JSON.stringify(rolledBackCountries)
        });
    }
  }
}
