export interface Country {
  id: string;
  labelEs: string;
  labelEn: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { id: "AF", labelEs: "Afganistán", labelEn: "Afghanistan", flag: "🇦🇫" },
  { id: "AL", labelEs: "Albania", labelEn: "Albania", flag: "🇦🇱" },
  { id: "DE", labelEs: "Alemania", labelEn: "Germany", flag: "🇩🇪" },
  { id: "AD", labelEs: "Andorra", labelEn: "Andorra", flag: "🇦🇩" },
  { id: "AO", labelEs: "Angola", labelEn: "Angola", flag: "🇦🇴" },
  { id: "AG", labelEs: "Antigua y Barbuda", labelEn: "Antigua and Barbuda", flag: "🇦🇬" },
  { id: "SA", labelEs: "Arabia Saudita", labelEn: "Saudi Arabia", flag: "🇸🇦" },
  { id: "DZ", labelEs: "Argelia", labelEn: "Algeria", flag: "🇩🇿" },
  { id: "AR", labelEs: "Argentina", labelEn: "Argentina", flag: "🇦🇷" },
  { id: "AM", labelEs: "Armenia", labelEn: "Armenia", flag: "🇦🇲" },
  { id: "AU", labelEs: "Australia", labelEn: "Australia", flag: "🇦🇺" },
  { id: "AT", labelEs: "Austria", labelEn: "Austria", flag: "🇦🇹" },
  { id: "AZ", labelEs: "Azerbaiyán", labelEn: "Azerbaijan", flag: "🇦🇿" },
  { id: "BS", labelEs: "Bahamas", labelEn: "Bahamas", flag: "🇧🇸" },
  { id: "BD", labelEs: "Bangladés", labelEn: "Bangladesh", flag: "🇧🇩" },
  { id: "BB", labelEs: "Barbados", labelEn: "Barbados", flag: "🇧🇧" },
  { id: "BH", labelEs: "Baréin", labelEn: "Bahrain", flag: "🇧🇭" },
  { id: "BE", labelEs: "Bélgica", labelEn: "Belgium", flag: "🇧🇪" },
  { id: "BZ", labelEs: "Belice", labelEn: "Belize", flag: "🇧🇿" },
  { id: "BJ", labelEs: "Benín", labelEn: "Benin", flag: "🇧🇯" },
  { id: "BY", labelEs: "Bielorrusia", labelEn: "Belarus", flag: "🇧🇾" },
  { id: "MM", labelEs: "Birmania", labelEn: "Myanmar", flag: "🇲🇲" },
  { id: "BO", labelEs: "Bolivia", labelEn: "Bolivia", flag: "🇧🇴" },
  { id: "BA", labelEs: "Bosnia y Herzegovina", labelEn: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { id: "BW", labelEs: "Botsuana", labelEn: "Botswana", flag: "🇧🇼" },
  { id: "BR", labelEs: "Brasil", labelEn: "Brazil", flag: "🇧🇷" },
  { id: "BN", labelEs: "Brunéi", labelEn: "Brunei", flag: "🇧🇳" },
  { id: "BG", labelEs: "Bulgaria", labelEn: "Bulgaria", flag: "🇧🇬" },
  { id: "BF", labelEs: "Burkina Faso", labelEn: "Burkina Faso", flag: "🇧🇫" },
  { id: "BI", labelEs: "Burundi", labelEn: "Burundi", flag: "🇧🇮" },
  { id: "BT", labelEs: "Bután", labelEn: "Bhutan", flag: "🇧🇹" },
  { id: "CV", labelEs: "Cabo Verde", labelEn: "Cape Verde", flag: "🇨🇻" },
  { id: "KH", labelEs: "Camboya", labelEn: "Cambodia", flag: "🇰🇭" },
  { id: "CM", labelEs: "Camerún", labelEn: "Cameroon", flag: "🇨🇲" },
  { id: "CA", labelEs: "Canadá", labelEn: "Canada", flag: "🇨🇦" },
  { id: "QA", labelEs: "Catar", labelEn: "Qatar", flag: "🇶🇦" },
  { id: "TD", labelEs: "Chad", labelEn: "Chad", flag: "🇹🇩" },
  { id: "CL", labelEs: "Chile", labelEn: "Chile", flag: "🇨🇱" },
  { id: "CN", labelEs: "China", labelEn: "China", flag: "🇨🇳" },
  { id: "CY", labelEs: "Chipre", labelEn: "Cyprus", flag: "🇨🇾" },
  { id: "VA", labelEs: "Ciudad del Vaticano", labelEn: "Vatican City", flag: "🇻🇦" },
  { id: "CO", labelEs: "Colombia", labelEn: "Colombia", flag: "🇨🇴" },
  { id: "KM", labelEs: "Comoras", labelEn: "Comoros", flag: "🇰🇲" },
  { id: "KP", labelEs: "Corea del Norte", labelEn: "North Korea", flag: "🇰🇵" },
  { id: "KR", labelEs: "Corea del Sur", labelEn: "South Korea", flag: "🇰🇷" },
  { id: "CI", labelEs: "Costa de Marfil", labelEn: "Ivory Coast", flag: "🇨🇮" },
  { id: "CR", labelEs: "Costa Rica", labelEn: "Costa Rica", flag: "🇨🇷" },
  { id: "HR", labelEs: "Croacia", labelEn: "Croatia", flag: "🇭🇷" },
  { id: "CU", labelEs: "Cuba", labelEn: "Cuba", flag: "🇨🇺" },
  { id: "DK", labelEs: "Dinamarca", labelEn: "Denmark", flag: "🇩🇰" },
  { id: "DM", labelEs: "Dominica", labelEn: "Dominica", flag: "🇩🇲" },
  { id: "EC", labelEs: "Ecuador", labelEn: "Ecuador", flag: "🇪🇨" },
  { id: "EG", labelEs: "Egipto", labelEn: "Egypt", flag: "🇪🇬" },
  { id: "SV", labelEs: "El Salvador", labelEn: "El Salvador", flag: "🇸��" },
  { id: "AE", labelEs: "Emiratos Árabes Unidos", labelEn: "United Arab Emirates", flag: "🇦🇪" },
  { id: "ER", labelEs: "Eritrea", labelEn: "Eritrea", flag: "🇪🇷" },
  { id: "SK", labelEs: "Eslovaquia", labelEn: "Slovakia", flag: "🇸🇰" },
  { id: "SI", labelEs: "Eslovenia", labelEn: "Slovenia", flag: "🇸🇮" },
  { id: "ES", labelEs: "España", labelEn: "Spain", flag: "🇪🇸" },
  { id: "US", labelEs: "Estados Unidos", labelEn: "United States", flag: "🇺🇸" },
  { id: "EE", labelEs: "Estonia", labelEn: "Estonia", flag: "🇪🇪" },
  { id: "ET", labelEs: "Etiopía", labelEn: "Ethiopia", flag: "🇪🇹" },
  { id: "PH", labelEs: "Filipinas", labelEn: "Philippines", flag: "🇵🇭" },
  { id: "FI", labelEs: "Finlandia", labelEn: "Finland", flag: "🇫🇮" },
  { id: "FJ", labelEs: "Fiyi", labelEn: "Fiji", flag: "🇫🇯" },
  { id: "FR", labelEs: "Francia", labelEn: "France", flag: "🇫🇷" },
  { id: "GA", labelEs: "Gabón", labelEn: "Gabon", flag: "🇬🇦" },
  { id: "GM", labelEs: "Gambia", labelEn: "Gambia", flag: "🇬🇲" },
  { id: "GE", labelEs: "Georgia", labelEn: "Georgia", flag: "🇬��" },
  { id: "GH", labelEs: "Ghana", labelEn: "Ghana", flag: "🇬🇭" },
  { id: "GD", labelEs: "Granada", labelEn: "Grenada", flag: "🇬🇩" },
  { id: "GR", labelEs: "Grecia", labelEn: "Greece", flag: "🇬🇷" },
  { id: "GT", labelEs: "Guatemala", labelEn: "Guatemala", flag: "🇬🇹" },
  { id: "GY", labelEs: "Guyana", labelEn: "Guyana", flag: "🇬🇾" },
  { id: "GN", labelEs: "Guinea", labelEn: "Guinea", flag: "🇬🇳" },
  { id: "GQ", labelEs: "Guinea ecuatorial", labelEn: "Equatorial Guinea", flag: "🇬🇶" },
  { id: "GW", labelEs: "Guinea-Bisáu", labelEn: "Guinea-Bissau", flag: "🇬🇼" },
  { id: "HT", labelEs: "Haití", labelEn: "Haiti", flag: "🇭🇹" },
  { id: "HN", labelEs: "Honduras", labelEn: "Honduras", flag: "🇭🇳" },
  { id: "HU", labelEs: "Hungría", labelEn: "Hungary", flag: "🇭🇺" },
  { id: "IN", labelEs: "India", labelEn: "India", flag: "🇮🇳" },
  { id: "ID", labelEs: "Indonesia", labelEn: "Indonesia", flag: "🇮🇩" },
  { id: "IQ", labelEs: "Irak", labelEn: "Iraq", flag: "🇮🇶" },
  { id: "IR", labelEs: "Irán", labelEn: "Iran", flag: "🇮🇷" },
  { id: "IE", labelEs: "Irlanda", labelEn: "Ireland", flag: "🇮🇪" },
  { id: "IS", labelEs: "Islandia", labelEn: "Iceland", flag: "🇮🇸" },
  { id: "MH", labelEs: "Islas Marshall", labelEn: "Marshall Islands", flag: "🇲🇭" },
  { id: "SB", labelEs: "Islas Salomón", labelEn: "Solomon Islands", flag: "🇸🇧" },
  { id: "IL", labelEs: "Israel", labelEn: "Israel", flag: "🇮🇱" },
  { id: "IT", labelEs: "Italia", labelEn: "Italy", flag: "🇮🇹" },
  { id: "JM", labelEs: "Jamaica", labelEn: "Jamaica", flag: "🇯🇲" },
  { id: "JP", labelEs: "Japón", labelEn: "Japan", flag: "🇯🇵" },
  { id: "JO", labelEs: "Jordania", labelEn: "Jordan", flag: "🇯🇴" },
  { id: "KZ", labelEs: "Kazajistán", labelEn: "Kazakhstan", flag: "🇰🇿" },
  { id: "KE", labelEs: "Kenia", labelEn: "Kenya", flag: "🇰🇪" },
  { id: "KG", labelEs: "Kirguistán", labelEn: "Kyrгызstan", flag: "🇰🇬" },
  { id: "KI", labelEs: "Kiribati", labelEn: "Kiribati", flag: "🇰🇮" },
  { id: "KW", labelEs: "Kuwait", labelEn: "Kuwait", flag: "🇰🇼" },
  { id: "LA", labelEs: "Laos", labelEn: "Laos", flag: "🇱🇦" },
  { id: "LS", labelEs: "Lesoto", labelEn: "Lesotho", flag: "🇱🇸" },
  { id: "LV", labelEs: "Letonia", labelEn: "Latvia", flag: "🇱🇻" },
  { id: "LB", labelEs: "Líbano", labelEn: "Lebanon", flag: "🇱🇧" },
  { id: "LR", labelEs: "Liberia", labelEn: "Liberia", flag: "🇱🇷" },
  { id: "LY", labelEs: "Libia", labelEn: "Libya", flag: "🇱🇾" },
  { id: "LI", labelEs: "Liechtenstein", labelEn: "Liechtenstein", flag: "🇱🇮" },
  { id: "LT", labelEs: "Lituania", labelEn: "Lithuania", flag: "🇱🇹" },
  { id: "LU", labelEs: "Luxemburgo", labelEn: "Luxembourg", flag: "🇱🇺" },
  { id: "MK", labelEs: "Macedonia del Norte", labelEn: "North Macedonia", flag: "🇲🇰" },
  { id: "MG", labelEs: "Madagascar", labelEn: "Madagascar", flag: "��🇬" },
  { id: "MY", labelEs: "Malasia", labelEn: "Malaysia", flag: "🇲🇾" },
  { id: "MW", labelEs: "Malaui", labelEn: "Malawi", flag: "🇲🇼" },
  { id: "MV", labelEs: "Maldivas", labelEn: "Maldives", flag: "🇲🇻" },
  { id: "ML", labelEs: "Malí", labelEn: "Mali", flag: "🇲🇱" },
  { id: "MT", labelEs: "Malta", labelEn: "Malta", flag: "🇲🇹" },
  { id: "MA", labelEs: "Marruecos", labelEn: "Morocco", flag: "🇲��" },
  { id: "MU", labelEs: "Mauricio", labelEn: "Mauritius", flag: "🇲🇺" },
  { id: "MR", labelEs: "Mauritania", labelEn: "Mauritania", flag: "🇲🇷" },
  { id: "MX", labelEs: "México", labelEn: "Mexico", flag: "🇲🇽" },
  { id: "FM", labelEs: "Micronesia", labelEn: "Micronesia", flag: "🇫🇲" },
  { id: "MD", labelEs: "Moldavia", labelEn: "Moldova", flag: "🇲🇩" },
  { id: "MC", labelEs: "Mónaco", labelEn: "Monaco", flag: "🇲🇨" },
  { id: "MN", labelEs: "Mongolia", labelEn: "Mongolia", flag: "🇲🇳" },
  { id: "ME", labelEs: "Montenegro", labelEn: "Montenegro", flag: "🇲🇪" },
  { id: "MZ", labelEs: "Mozambique", labelEn: "Mozambique", flag: "🇲🇿" },
  { id: "NA", labelEs: "Namibia", labelEn: "Namibia", flag: "🇳🇦" },
  { id: "NR", labelEs: "Nauru", labelEn: "Nauru", flag: "🇳🇷" },
  { id: "NP", labelEs: "Nepal", labelEn: "Nepal", flag: "🇳🇵" },
  { id: "NI", labelEs: "Nicaragua", labelEn: "Nicaragua", flag: "🇳🇮" },
  { id: "NE", labelEs: "Níger", labelEn: "Niger", flag: "🇳🇪" },
  { id: "NG", labelEs: "Nigeria", labelEn: "Nigeria", flag: "🇳🇬" },
  { id: "NO", labelEs: "Noruega", labelEn: "Norway", flag: "🇳🇴" },
  { id: "NZ", labelEs: "Nueva Zelanda", labelEn: "New Zealand", flag: "🇳🇿" },
  { id: "OM", labelEs: "Omán", labelEn: "Oman", flag: "🇴🇲" },
  { id: "NL", labelEs: "Países Bajos", labelEn: "Netherlands", flag: "🇳🇱" },
  { id: "PK", labelEs: "Pakistán", labelEn: "Pakistan", flag: "🇵🇰" },
  { id: "PW", labelEs: "Palaos", labelEn: "Palau", flag: "🇵🇼" },
  { id: "PA", labelEs: "Panamá", labelEn: "Panama", flag: "��🇦" },
  { id: "PG", labelEs: "Papúa Nueva Guinea", labelEn: "Papua New Guinea", flag: "🇵🇬" },
  { id: "PY", labelEs: "Paraguay", labelEn: "Paraguay", flag: "🇵🇾" },
  { id: "PE", labelEs: "Perú", labelEn: "Peru", flag: "🇵🇪" },
  { id: "PL", labelEs: "Polonia", labelEn: "Poland", flag: "🇵🇱" },
  { id: "PT", labelEs: "Portugal", labelEn: "Portugal", flag: "��🇹" },
  { id: "GB", labelEs: "Reino Unido", labelEn: "United Kingdom", flag: "🇬🇧" },
  { id: "CF", labelEs: "República Centroafricana", labelEn: "Central African Republic", flag: "🇨🇫" },
  { id: "CZ", labelEs: "República Checa", labelEn: "Czech Republic", flag: "🇨🇿" },
  { id: "CG", labelEs: "República del Congo", labelEn: "Republic of the Congo", flag: "🇨🇬" },
  { id: "CD", labelEs: "República Democrática del Congo", labelEn: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { id: "DO", labelEs: "República Dominicana", labelEn: "Dominican Republic", flag: "🇩🇴" },
  { id: "RW", labelEs: "Ruanda", labelEn: "Rwanda", flag: "🇷🇼" },
  { id: "RO", labelEs: "Rumanía", labelEn: "Romania", flag: "🇷🇴" },
  { id: "RU", labelEs: "Rusia", labelEn: "Russia", flag: "🇷🇺" },
  { id: "WS", labelEs: "Samoa", labelEn: "Samoa", flag: "🇼🇸" },
  { id: "KN", labelEs: "San Cristóbal y Nieves", labelEn: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { id: "SM", labelEs: "San Marino", labelEn: "San Marino", flag: "🇸🇲" },
  { id: "VC", labelEs: "San Vicente y las Granadinas", labelEn: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { id: "LC", labelEs: "Santa Lucía", labelEn: "Saint Lucia", flag: "🇱🇨" },
  { id: "ST", labelEs: "Santo Tomé y Príncipe", labelEn: "Sao Tome and Principe", flag: "🇸🇹" },
  { id: "SN", labelEs: "Senegal", labelEn: "Senegal", flag: "🇸🇳" },
  { id: "RS", labelEs: "Serbia", labelEn: "Serbia", flag: "🇷🇸" },
  { id: "SC", labelEs: "Seychelles", labelEn: "Seychelles", flag: "🇸🇨" },
  { id: "SL", labelEs: "Sierra Leona", labelEn: "Sierra Leone", flag: "��🇱" },
  { id: "SG", labelEs: "Singapur", labelEn: "Singapore", flag: "🇸🇬" },
  { id: "SY", labelEs: "Siria", labelEn: "Syria", flag: "🇸🇾" },
  { id: "SO", labelEs: "Somalia", labelEn: "Somalia", flag: "🇸🇴" },
  { id: "LK", labelEs: "Sri Lanka", labelEn: "Sri Lanka", flag: "🇱🇰" },
  { id: "SZ", labelEs: "Suazilandia", labelEn: "Eswatini", flag: "🇸🇿" },
  { id: "ZA", labelEs: "Sudáfrica", labelEn: "South Africa", flag: "🇿🇦" },
  { id: "SD", labelEs: "Sudán", labelEn: "Sudan", flag: "🇸🇩" },
  { id: "SS", labelEs: "Sudán del Sur", labelEn: "South Sudan", flag: "🇸🇸" },
  { id: "SE", labelEs: "Suecia", labelEn: "Sweden", flag: "🇸🇪" },
  { id: "CH", labelEs: "Suiza", labelEn: "Switzerland", flag: "🇨🇭" },
  { id: "SR", labelEs: "Surinam", labelEn: "Suriname", flag: "🇸🇷" },
  { id: "TH", labelEs: "Tailandia", labelEn: "Thailand", flag: "🇹🇭" },
  { id: "TZ", labelEs: "Tanzania", labelEn: "Tanzania", flag: "🇹🇿" },
  { id: "TJ", labelEs: "Tayikistán", labelEn: "Tajikistan", flag: "🇹🇯" },
  { id: "TL", labelEs: "Timor Oriental", labelEn: "East Timor", flag: "��🇱" },
  { id: "TG", labelEs: "Togo", labelEn: "Togo", flag: "🇹🇬" },
  { id: "TO", labelEs: "Tonga", labelEn: "Tonga", flag: "🇹🇴" },
  { id: "TT", labelEs: "Trinidad y Tobago", labelEn: "Trinidad and Tobago", flag: "🇹🇹" },
  { id: "TN", labelEs: "Túnez", labelEn: "Tunisia", flag: "🇹🇳" },
  { id: "TM", labelEs: "Turkmenistán", labelEn: "Turkmenistan", flag: "🇹🇲" },
  { id: "TR", labelEs: "Turquía", labelEn: "Turkey", flag: "🇹🇷" },
  { id: "TV", labelEs: "Tuvalu", labelEn: "Tuvalu", flag: "🇹🇻" },
  { id: "UA", labelEs: "Ucrania", labelEn: "Ukraine", flag: "🇺🇦" },
  { id: "UG", labelEs: "Uganda", labelEn: "Uganda", flag: "🇺🇬" },
  { id: "UY", labelEs: "Uruguay", labelEn: "Uruguay", flag: "🇺🇾" },
  { id: "UZ", labelEs: "Uzbekistán", labelEn: "Uzbekistan", flag: "🇺🇿" },
  { id: "VU", labelEs: "Vanuatu", labelEn: "Vanuatu", flag: "🇻🇺" },
  { id: "VE", labelEs: "Venezuela", labelEn: "Venezuela", flag: "🇻🇪" },
  { id: "VN", labelEs: "Vietnam", labelEn: "Vietnam", flag: "🇻🇳" },
  { id: "YE", labelEs: "Yemen", labelEn: "Yemen", flag: "🇾🇪" },
  { id: "DJ", labelEs: "Yibuti", labelEn: "Djibouti", flag: "🇩🇯" },
  { id: "ZM", labelEs: "Zambia", labelEn: "Zambia", flag: "🇿🇲" },
  { id: "ZW", labelEs: "Zimbabue", labelEn: "Zimbabwe", flag: "🇿🇼" }
];

import { get } from "svelte/store";
import { languageStore } from "$lib/stores/ui";

export function getCountryFlag(identifier: string): string {
  if (!identifier) return "🌍";
  const match = COUNTRIES.find(c => c.id.toLowerCase() === identifier.toLowerCase() || c.labelEs.toLowerCase() === identifier.toLowerCase() || c.labelEn.toLowerCase() === identifier.toLowerCase());
  return match ? match.flag : "🌍";
}

export function getCountryName(identifier: string, forceLang?: "es" | "en"): string {
  if (!identifier) return "";
  const match = COUNTRIES.find(c => c.id.toLowerCase() === identifier.toLowerCase() || c.labelEs.toLowerCase() === identifier.toLowerCase() || c.labelEn.toLowerCase() === identifier.toLowerCase());
  if (!match) return identifier;
  
  const lang = forceLang || get(languageStore);
  if (lang === "en") return match.labelEn;
  return match.labelEs;
}
